export const projects = [
  {
    id: "orda",
    slug: "orda",
    name: "ЖК ORDA",
    nameShort: "ORDA",
    image: "/images/dostar.jpg",
    address: "ул. Сакена Жунусова, 41, Кокшетау",
    floors: 9,
    sections: 4,
    apartments: "1–3 комнатные",
    finishing: "Предчистовая отделка",
    ceilingHeight: "3 м",
    status: "Строится" as const,
    statusNote: "Ждем старт продаж",
    class: "Комфорт+",
    construction: "Монолитно-каркасная",
    parking: "Подземный, гостевой",
    heating: "Центральное",
    elevator: "Да",
    walls: "Газоблок",
    facade: "Облицовочный кирпич",
    territory: "Детская площадка, спортивная площадка",
    description:
      "ЖК ORDA — современный жилой комплекс класса «Комфорт+» по ул. Сакена Жунусова, 41. 9-этажный монолитно-каркасный дом из 4 секций с газоблочными стенами и облицовочным кирпичным фасадом. Подземный и гостевой паркинг, детская и спортивная площадки во дворе.",
    features: [
      "Класс Комфорт+",
      "9 этажей, 4 секции",
      "Монолитно-каркасная технология",
      "Газоблочные стены",
      "Облицовочный кирпичный фасад",
      "Подземный и гостевой паркинг",
      "Детская и спортивная площадки",
      "Центральное отопление",
    ],
    infrastructure: [
      "Развитая инфраструктура района",
      "Общественный транспорт — в шаговой доступности",
      "Социально-значимые объекты поблизости",
    ],
  },
  {
    id: "dostar",
    slug: "dostar",
    name: "ЖК DOSTAR",
    nameShort: "DOSTAR",
    image: "https://storage.googleapis.com/bd-kz-01/buildings-v2/1280x960/26756.jpg",
    address: "ул. Свердлова, 1, Кокшетау",
    floors: 9,
    sections: 2,
    totalApartments: 52,
    apartments: "2–3 комнатные",
    finishing: "Черновая отделка",
    ceilingHeight: "3 м",
    area: "50,56–107,34 м²",
    pricePerSqm: "от 360 000 ₸",
    status: "Сдан" as const,
    statusNote: "Сдан в 2023",
    class: "Комфорт",
    construction: "Кирпичная",
    parking: "Наземный",
    heating: "Центральное",
    elevator: "Пассажирский",
    walls: "Кирпич",
    insulation: "Минеральная вата",
    facade: "Облицовочный кирпич",
    territory: "Закрытый двор, круглосуточное видеонаблюдение",
    windows: "Увеличенные оконные проёмы",
    description:
      "Жилой комплекс Dostar – стильная новостройка средней этажности с комфортабельными квартирами, расположенная в уютном районе Кокшетау. Всего в 180 метрах от набережной реки Кылшакты. Современная архитектура с элементами классического европейского стиля, надёжные материалы и закрытый благоустроенный двор.",
    features: [
      "Кирпичный дом, утеплённый минеральной ватой",
      "Высота потолков 3 метра",
      "Увеличенные оконные проёмы",
      "Закрытый двор с видеонаблюдением",
      "Бесшумные скоростные лифты",
      "Декоративная подсветка фасада",
      "Зоны отдыха и детские площадки во дворе",
      "180 м до набережной реки Кылшакты",
    ],
    infrastructure: [
      "Школа №8 и детский сад «Алёнушка» — рядом",
      "ТЦ «Шадияр» и «Жибек» — в шаговой доступности",
      "Остановка автобусов №13, №23 — 240 м (ул. Сулейменова)",
      "Поликлиника №1 и госпиталь — до 2 км",
      "Аэропорт «Кокшетау» — 20 минут езды",
    ],
  },
  {
    id: "tumar-deluxe",
    slug: "tumar-deluxe",
    name: "ЖК Tumar Deluxe",
    nameShort: "Tumar Deluxe",
    image: "https://storage.googleapis.com/bd-kz-01/buildings-v2/1280x960/35042.jpg",
    address: "ул. Канай би, 32а, Кокшетау",
    floors: 12,
    sections: 3,
    totalApartments: 99,
    apartments: "1–4 комнатные",
    finishing: "Предчистовая отделка",
    ceilingHeight: "3 м",
    area: "45,09–155,63 м²",
    pricePerSqm: "от 515 000 ₸",
    status: "Сдан" as const,
    statusNote: "Сдан в 2 кв. 2025",
    class: "Бизнес",
    construction: "Монолитно-каркасная",
    parking: "Подземный, гостевой",
    heating: "Центральное",
    elevator: "Грузопассажирский, пассажирский",
    walls: "Кирпич (толщина 77 см)",
    facade: "Облицовочный кирпич",
    territory: "Закрытый двор, видеонаблюдение, детская площадка",
    windows: "Увеличенные оконные проёмы 1,8 м",
    description:
      "ЖК Tumar Deluxe в Кокшетау – продуманный до мелочей комплекс бизнес-класса, расположенный в «золотом квадрате» города по ул. Канай би, 32а. 5 минут пешком до озера Копа, 10 минут до Городского парка. Авторский дизайн подъездов, монолитно-каркасный каркас, предчистовая отделка с биометрическими замками и IP-домофонами.",
    features: [
      "Бизнес-класс — всего 99 квартир",
      "12 этажей, монолитно-каркасная технология",
      "Увеличенные окна 1,8 м и двери 2,4 м",
      "Потолки 3,0 м",
      "Авторский дизайн подъездов",
      "Подземный паркинг",
      "Предчистовая отделка с биометрическими замками",
      "5 мин пешком до озера Копа",
    ],
    infrastructure: [
      "Озеро Копа — 5 мин пешком",
      "Городской парк — 10 мин пешком",
      "Остановки автобусов №1, №8, №14 — 280 м",
      "ТЦ «Айнерим», Satti, «Арбат» — в радиусе 2 км",
      "КГУ им. Ш. Уалиханова и колледжи — рядом",
    ],
  },
]

export const floorPlans = [
  // ЖК DOSTAR — 7 планировок
  { id: 1, projectSlug: "dostar", projectName: "ЖК DOSTAR", rooms: 2, area: 50.56, price: 18201600, pricePerSqm: 360000, image: "https://storage.googleapis.com/bd-kz-01/layouts-v2/340x340/150891.jpg" },
  { id: 2, projectSlug: "dostar", projectName: "ЖК DOSTAR", rooms: 2, area: 65.58, price: 23608800, pricePerSqm: 360000, image: "https://storage.googleapis.com/bd-kz-01/layouts-v2/340x340/161816.jpg" },
  { id: 3, projectSlug: "dostar", projectName: "ЖК DOSTAR", rooms: 3, area: 92.83, price: 33418800, pricePerSqm: 360000, image: "https://storage.googleapis.com/bd-kz-01/layouts-v2/340x340/110033.jpg" },
  { id: 4, projectSlug: "dostar", projectName: "ЖК DOSTAR", rooms: 3, area: 99.03, price: 35650800, pricePerSqm: 360000, image: "https://storage.googleapis.com/bd-kz-01/layouts-v2/340x340/150891.jpg" },
  { id: 5, projectSlug: "dostar", projectName: "ЖК DOSTAR", rooms: 3, area: 100.26, price: 36093600, pricePerSqm: 360000, image: "https://storage.googleapis.com/bd-kz-01/layouts-v2/340x340/161816.jpg" },
  { id: 6, projectSlug: "dostar", projectName: "ЖК DOSTAR", rooms: 3, area: 106.09, price: 38192400, pricePerSqm: 360000, image: "https://storage.googleapis.com/bd-kz-01/layouts-v2/340x340/110033.jpg" },
  { id: 7, projectSlug: "dostar", projectName: "ЖК DOSTAR", rooms: 3, area: 107.34, price: 38642400, pricePerSqm: 360000, image: "https://storage.googleapis.com/bd-kz-01/layouts-v2/340x340/150891.jpg" },

  // ЖК Tumar Deluxe — 6 планировок
  { id: 8, projectSlug: "tumar-deluxe", projectName: "ЖК Tumar Deluxe", rooms: 1, area: 49.05, price: 25506000, pricePerSqm: 520000, image: "https://storage.googleapis.com/bd-kz-01/layouts-v2/340x340/161816.jpg" },
  { id: 9, projectSlug: "tumar-deluxe", projectName: "ЖК Tumar Deluxe", rooms: 2, area: 82.74, price: 42611100, pricePerSqm: 515000, image: "https://storage.googleapis.com/bd-kz-01/layouts-v2/340x340/150891.jpg" },
  { id: 10, projectSlug: "tumar-deluxe", projectName: "ЖК Tumar Deluxe", rooms: 2, area: 83.08, price: 42786200, pricePerSqm: 515000, image: "https://storage.googleapis.com/bd-kz-01/layouts-v2/340x340/110033.jpg" },
  { id: 11, projectSlug: "tumar-deluxe", projectName: "ЖК Tumar Deluxe", rooms: 3, area: 114.78, price: 59111700, pricePerSqm: 515000, image: "https://storage.googleapis.com/bd-kz-01/layouts-v2/340x340/150891.jpg" },
  { id: 12, projectSlug: "tumar-deluxe", projectName: "ЖК Tumar Deluxe", rooms: 3, area: 131.84, price: 67897600, pricePerSqm: 515000, image: "https://storage.googleapis.com/bd-kz-01/layouts-v2/340x340/161816.jpg" },
  { id: 13, projectSlug: "tumar-deluxe", projectName: "ЖК Tumar Deluxe", rooms: 4, area: 155.63, price: 80149450, pricePerSqm: 515000, image: "https://storage.googleapis.com/bd-kz-01/layouts-v2/340x340/110033.jpg" },
]

export const mortgagePrograms = [
  {
    id: "baspana-hit",
    name: "Баспана Хит",
    rate: 5,
    maxTerm: 25,
    downPayment: 20,
    description: "Государственная ипотечная программа с льготной ставкой для приобретения первичного жилья.",
  },
  {
    id: "7-20-25",
    name: "7-20-25",
    rate: 7,
    maxTerm: 25,
    downPayment: 20,
    description: "Программа доступного жилья: 7% годовых, 20% первоначальный взнос, на 25 лет.",
  },
  {
    id: "nauryz",
    name: "Наурыз",
    rate: 3.5,
    maxTerm: 25,
    downPayment: 20,
    description: "Льготная ипотечная программа с минимальной ставкой для социально уязвимых категорий.",
  },
  {
    id: "nauryz-zhumysker",
    name: "Наурыз Жумыскер",
    rate: 4,
    maxTerm: 25,
    downPayment: 20,
    description: "Программа для работающих граждан с привлекательной процентной ставкой.",
  },
]

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("ru-KZ").format(price) + " ₸"
}
