export const projects = [
  {
    id: "chicago",
    slug: "chicago",
    name: "ЖК CHICAGO",
    nameShort: "CHICAGO",
    image: "/images/hero-building.jpg",
    address: "ул. Еркина Ауельбекова, 120Б, Кокшетау",
    floors: 10,
    sections: 2,
    apartments: "1–4 комнатные",
    finishing: "Премиальная черновая",
    ceilingHeight: "3.0 м",
    status: "В продаже" as const,
    statusNote: "Сдача в 1 кв. 2026",
    class: "Бизнес",
    construction: "Кирпичная",
    parking: "Наземный/Закрытый",
    heating: "Центральное",
    elevator: "Сквозные бесшумные лифты",
    walls: "Кирпич",
    facade: "Премиальная отделка",
    territory: "Закрытый двор, велопарковки, видеодомофония, колясочные",
    description:
      "ЖК CHICAGO — это современный жилой комплекс бизнес-класса в самом сердце Кокшетау. Уникальная архитектура, сквозные лифты и высокий уровень безопасности создают новый стандарт комфортной жизни.",
    features: [
      "Бизнес-класс",
      "Сквозные лифты",
      "Закрытый двор",
      "Велопарковки и колясочные",
      "Видеодомофония",
    ],
    area: "46.7–126 м²",
    pricePerSqm: "от 350 000 ₸",
    infrastructure: [
      "Центр города",
      "Рядом школы и госучреждения",
      "Удобная транспортная развязка",
    ],
  },
  {
    id: "turkestan-3",
    slug: "turkestan-3",
    name: "ЖК TURKESTAN III",
    nameShort: "TURKESTAN III",
    image: "/images/hero-building.jpg",
    address: "ул. Ермека Серкебаева, 33, Кокшетау",
    floors: 9,
    sections: 3,
    apartments: "1–4 комнатные",
    finishing: "Улучшенная черновая",
    ceilingHeight: "2.8 м",
    area: "35–117 м²",
    status: "В продаже" as const,
    statusNote: "Строится",
    class: "Комфорт",
    construction: "Кирпичная",
    parking: "Наземный паркинг",
    heating: "Центральное",
    walls: "Кирпич",
    facade: "Облицовочный кирпич",
    territory: "Благоустроенный двор, детские площадки",
    description:
      "ЖК TURKESTAN III — это продолжение успешной серии жилых комплексов в спальном районе города. Проверенное качество кирпичного домостроения и улучшенные планировки для вашей семьи.",
    features: [
      "Кирпичный дом",
      "Улучшенные планировки",
      "Благоустроенный двор",
      "Тихий район",
    ],
    pricePerSqm: "от 310 000 ₸",
    infrastructure: [
      "Развивающийся спальный район",
      "Школы и магазины в пешей доступности",
    ],
  },
  {
    id: "boston",
    slug: "boston",
    name: "ЖК BOSTON",
    nameShort: "BOSTON",
    image: "/images/hero-building.jpg",
    address: "г. Кокшетау",
    floors: 9,
    sections: 2,
    apartments: "1–3 комнатные",
    finishing: "Сдано",
    ceilingHeight: "2.8 м",
    status: "Сдан" as const,
    statusNote: "Продажи завершены",
    class: "Комфорт",
    construction: "Кирпичная",
    parking: "Гостевой",
    heating: "Центральное",
    walls: "Кирпич",
    facade: "Облицовочный кирпич",
    territory: "Детская площадка",
    description:
      "ЖК BOSTON — успешно реализованный проект компании КомфортСтрой2020. Качественное жилье в современном исполнении, уже радующее сотни семей.",
    features: [
      "Кирпичная технология",
      "Проверенный временем проект",
      "Развитая территория",
    ],
    area: "38–95 м²",
    pricePerSqm: "Продано",
    infrastructure: [
      "Тихий район",
      "Зона отдыха",
    ],
  },
  {
    id: "turkestan-1-2",
    slug: "turkestan-prev",
    name: "ЖК TURKESTAN I, II",
    nameShort: "TURKESTAN",
    image: "/images/hero-building.jpg",
    address: "ул. С. Сейфуллина, 84, Кокшетау",
    floors: 9,
    sections: 4,
    apartments: "Сдано",
    finishing: "Сдано",
    ceilingHeight: "2.8 м",
    status: "Сдан" as const,
    statusNote: "Введен в эксплуатацию",
    class: "Комфорт",
    construction: "Кирпичная",
    parking: "Наземный",
    heating: "Центральное",
    walls: "Кирпич",
    facade: "Облицовочный кирпич",
    territory: "Полностью благоустроен",
    description:
      "Первые проекты в серии TURKESTAN, заложившие основу репутации компании КомфортСтрой2020 как надежного застройщика кирпичных домов.",
    features: [
      "Историческая надежность",
      "Кирпичное исполнение",
      "Благоустроенный двор",
    ],
    area: "35–110 м²",
    pricePerSqm: "Продано",
    infrastructure: [
      "Обжитой район",
      "Все сервисы рядом",
    ],
  },
]

export const floorPlans = [
  { id: 1, projectSlug: "chicago", projectName: "ЖК CHICAGO", rooms: 1, area: 46.7, price: 16345000, pricePerSqm: 350000, image: "/images/hero-building.jpg" },
  { id: 2, projectSlug: "chicago", projectName: "ЖК CHICAGO", rooms: 2, area: 70.1, price: 24535000, pricePerSqm: 350000, image: "/images/hero-building.jpg" },
  { id: 3, projectSlug: "turkestan-3", projectName: "ЖК TURKESTAN III", rooms: 1, area: 35.5, price: 11005000, pricePerSqm: 310000, image: "/images/hero-building.jpg" },
  { id: 4, projectSlug: "turkestan-3", projectName: "ЖК TURKESTAN III", rooms: 3, area: 85.0, price: 26350000, pricePerSqm: 310000, image: "/images/hero-building.jpg" },
]

export const mortgagePrograms = [
  {
    id: "otau",
    name: "Отау",
    rate: 9,
    maxTerm: 19,
    downPayment: 20,
    description: "Специальная ипотечная программа от Отбасы банка. Ставка 9% годовых.",
  },
  {
    id: "7-20-25",
    name: "7-20-25",
    rate: 7,
    maxTerm: 25,
    downPayment: 20,
    description: "Программа доступного жилья от КФУ для первичного рынка.",
  },
  {
    id: "installment",
    name: "Рассрочка",
    rate: 0,
    maxTerm: 2,
    downPayment: 30,
    description: "Беспроцентная рассрочка от застройщика КомфортСтрой2020.",
  },
]

export function formatPrice(price: number | string): string {
  if (typeof price === "string") return price
  return new Intl.NumberFormat("ru-KZ").format(price) + " ₸"
}
